spring:
  application:
    name: spring-cloud-zuul
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #集群配置
    register-with-eureka: true
  instance:
    instance-id: spring-cloud-zuul-9527
    prefer-ip-address: true # 才能自动获取本机url 不配置的话会报错
zuul:
  routes:
    springcloud-provider-dept.serviceId: springClod-producer-dept
    springcloud-provider-dept.path: /dept/**
  ignored-services: springClod-producer-dept


