server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com # eureka的服务端的实例名字
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # fetch-registry设置为false表示自己是注册中心
    service-url: # 监控页面 单个配置  http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 集群配置