server:
  port: 3344
spring:
  application:
    name: springCloud-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhong-hongqiang/spring-cloud-config.git
          search-paths:
            - springCloud-config
          label: master